audreyfeldroy/cookiecutter-pypackage

{{cookiecutter.repo_name}}/setup.py
This change ensures the file handles are properly closed in setup.py.
=> Ensure file handles are closed using with statement

{{cookiecutter.repo_name}}/Makefile
A simple little addendum to the Makefile.
=> Added an install option to Makefile

{{cookiecutter.repo_name}}/README.rst
Use shields.io to have the same badge style. Remove duplicated badge for pypi information
=> Change badges source

.travis.yml, README.rst
travis-ci has to be turned on for this repo still :)
=> Travis-ci and badge test cookiecutter-pypackage

{{cookiecutter.repo_name}}/requirements_dev.txt
Now that we have a dev requirements file, we can close issue #45 :)
=> Add other packages needed for development (fixes #45)

{{cookiecutter.project_slug}}/tox.ini
Hey @audreyr 
This fixes #70.
I thought it was a good idea to leave the section commented with a note there, for folks who will pin the versions later.
Does this look good?
=> Comment deps section in tox.ini and add note about pinning

README.rst
Changes to the forked version:
* Required packages are not hardcoded in the ``setup.py`` file. All the required packages are inside the ``requirements`` folder.
* Package requirements are broken down into separate files::
.. code:: bash
├── requirements
│   ├── dev.txt
│   ├── prod.txt
│   ├── test.txt
* Creates a default class based on the package name.
=> Add a forked version.

{{cookiecutter.project_slug}}/CONTRIBUTING.rst, {{cookiecutter.project_slug}}/HISTORY.rst, {{cookiecutter.project_slug}}/README.rst, {{cookiecutter.project_slug}}/docs/installation.rst, {{cookiecutter.project_slug}}/docs/usage.rst
* `.. highlight:: shell` changes the default syntax highlighting for the entire page
* some linters raise an error if the length of the header line isn't `==` length of the text
* reasoning: this repo is forked a lot, so a namespace is appropriate.  This makes it easier to copy and paste, and add your fork.
=> fixed minor issues in the docs

docs/travis_pypi_setup.rst, docs/tutorial.rst
This addresses issue #83, adding more details about Travis PyPI setup.
Does this look good?
=> Updating tutorial and travis/pypi setup details

cookiecutter.json
=> Update defaults for year and release_date

{{cookiecutter.project_slug}}/MANIFEST.in
The docs may contain related images which were ignored by MANIFEST.in
=> Include images in documentation

{{cookiecutter.project_slug}}/docs/installation.rst
Add proper highlight support for shell commands.
=> Proper highlight shell commands (fixes #94)

tests/test_bake_project.py, {{cookiecutter.project_slug}}/setup.py
fixing issue https://github.com/audreyr/cookiecutter-pypackage/issues/113
=> fixed syntax error when github name has quotes

tests/test_bake_project.py, {{cookiecutter.project_slug}}/Makefile
- Changed Makefile 'help' command to autogenerate help from command comments
- Created a test to run 'make help' and assert there is a command in 'make help'
=> Add tests for Makefile. Close #109

cookiecutter.json, tests/test_bake_project.py, {{cookiecutter.project_slug}}/HISTORY.rst, {{cookiecutter.project_slug}}/LICENSE, {{cookiecutter.project_slug}}/docs/conf.py
=> Simplify cookiecutter

docs/tutorial.rst
Added information and resources to make the proccess a little more understandable
=> Tutorial _sprints_

requirements_dev.txt
New requirements file with dependencies necessary for test file
=> Added requirements file with package dependencies for test file

CONTRIBUTING.rst
=> Updated Contribute.rst

tests/test_bake_project.py
=> added more tests

cookiecutter.json, tests/test_bake_project.py, {{cookiecutter.project_slug}}/setup.py
=> Fix license classifiers in setup.py

.gitignore
=> Update .gitignore from OSX system files

{{cookiecutter.project_slug}}/tox.ini
=> Add flake8 to generated project's tox.ini

cookiecutter.json, hooks/post_gen_project.py, tests/test_bake_project.py
=> Make authors optional

cookiecutter.json, tests/test_bake_project.py, {{cookiecutter.project_slug}}/LICENSE, {{cookiecutter.project_slug}}/README.rst, {{cookiecutter.project_slug}}/setup.py
Fixes #171 , generated README now accepts template value for license.
=> 171 template readme license

hooks/post_gen_project.py, tests/test_bake_project.py, {{cookiecutter.project_slug}}/docs/index.rst
=> Fix docs due to missing author file

CONTRIBUTING.rst
Added section on adding new tests when fixing bug or adding feature to contributing
=> added new test section to contributing

docs/troubleshooting.rst, docs/tutorial.rst, {{cookiecutter.project_slug}}/docs/troubleshooting.rst
Added troubleshooting doc. Update tutorial to make it more clear and fix up some rst issues. Some of the Windows issues I put into the tutorial, some into the troubleshooting doc. Please carefully read through what I wrote for Step 5 & 6. I'm not sure I did it all correctly, but it worked for me. I did not attempt to release it on PyPI, so Step 7 is essentially unchanged.
=> Update tutorial and add troubleshooting doc. Close #174

CONTRIBUTING.rst, requirements_dev.txt, tox.ini
I have added sphinx build in tox.
=> Add sphinx doc build at tox

{{cookiecutter.project_slug}}/Makefile
Hi,
Thanks for an awesome template.  Added clean and clean-test to .PHONY target list and moved the commands for the clean target to the dependency list for the clean target. 
Hope this helps,
chris
=> Fix for issue #199 make clean target failing

{{cookiecutter.project_slug}}/docs/installation.rst
Is this what you were thinking about for issue 190?
=> Prefer pip installation. Close #190

README.rst, docs/tutorial.rst, {{cookiecutter.project_slug}}/README.rst
Implements #207
I've crated a new Step 7 and moved Step 7 to Step 8. Is this what you had in mind @audreyr?
=> Add pyup.io instructions

{{cookiecutter.project_slug}}/.gitignore
ignore .python-version file ( a pyenv configuration file)
https://github.com/yyuu/pyenv#choosing-the-python-version
=> ignore .python-version file ( a pyenv configuration file)

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/cli.py
Hi Audrey,
thx for cookiecutter :-)
{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/cli.py:5:1: E302 expected 2 blank lines, found 1
{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/cli.py:9:17: E127 continuation line over-indented for visual indent
=> pep8ed cli.py

{{cookiecutter.project_slug}}/tests/test_{{cookiecutter.project_slug}}.py
My apologies again for missing this typo. @eliasdorneles
=> Renamed r to response in sample pytest test function

{{cookiecutter.project_slug}}/setup.py, {{cookiecutter.project_slug}}/tests/__init__.py, {{cookiecutter.project_slug}}/tests/test_{{cookiecutter.project_slug}}.py, {{cookiecutter.project_slug}}/travis_pypi_setup.py, {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/__init__.py, {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/cli.py, {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}.py
Mostly cosmetic changes.  Fix docstrings/blank lines, and remove unused imports.
=> Conform to PEP 8

tests/test_bake_project.py, {{cookiecutter.project_slug}}/requirements_dev.txt, {{cookiecutter.project_slug}}/setup.cfg, {{cookiecutter.project_slug}}/setup.py
That is, make 'setup.py test' use pytest if pytest is enabled.
=> Integrate pytest into setup.py

README.rst
I added my fork that uses the punch version updater instead of bumpversion
=> lgiordani fork added

CONTRIBUTING.rst, README.rst, tox.ini, {{cookiecutter.project_slug}}/CONTRIBUTING.rst, {{cookiecutter.project_slug}}/Makefile, {{cookiecutter.project_slug}}/setup.py, {{cookiecutter.project_slug}}/tox.ini
http://blog.pytest.org/2016/whats-new-in-pytest-30/
https://twitter.com/hashtag/dropthedot
=> Use pytest instead of py.test per upstream recommendation, #dropthedot

CONTRIBUTING.rst
Fixed lists formatting and lines length.
=> Update formatting of CONTRIBUTING.rst

appveyor.yml, tox.ini
=> Fix failed appveyor build

.travis.yml, CONTRIBUTING.rst, README.rst, appveyor.yml, setup.py, tests/test_bake_project.py, tox.ini, {{cookiecutter.project_slug}}/.travis.yml, {{cookiecutter.project_slug}}/CONTRIBUTING.rst, {{cookiecutter.project_slug}}/tox.ini
=> add python3.7 support

.travis.yml, CONTRIBUTING.rst, setup.py, tox.ini, {{cookiecutter.project_slug}}/.travis.yml, {{cookiecutter.project_slug}}/CONTRIBUTING.rst, {{cookiecutter.project_slug}}/setup.py, {{cookiecutter.project_slug}}/tox.ini
=> Include Python 3.8 support

appveyor.yml
=> add appveyor py38

.travis.yml, appveyor.yml, docs/conf.py, tests/test_bake_project.py, {{cookiecutter.project_slug}}/Makefile, {{cookiecutter.project_slug}}/docs/conf.py, {{cookiecutter.project_slug}}/setup.py, {{cookiecutter.project_slug}}/tests/__init__.py, {{cookiecutter.project_slug}}/tests/test_{{cookiecutter.project_slug}}.py, {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/__init__.py, {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/cli.py, {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}.py
For #405. 
Complements https://github.com/audreyr/cookiecutter-pypackage/pull/543.
=> Remove redundant Python 2 code

{{cookiecutter.project_slug}}/tox.ini
Note the `Makfile` is already doing so via the `lint` target.
=> Also runs linter on tests folder in tox.ini

README.rst
This fork has switched to using Poetry for package management
=> Update fork description

docs/prompts.rst
I recently created a new project using `cookiecutter-pypackage`. A few of the prompts that I got did not match the ones mentioned in the documentation. This commit includes these.
=> Updated prompts.rst

{{cookiecutter.project_slug}}/.gitignore
https://rider-support.jetbrains.com/hc/en-us/articles/207097529-What-is-the-idea-folder-
=> Add `.idea` folder to gitignore for IntelliJ

.gitignore
Ignore the virtual environment directory
=> Ignore venv directory

{{cookiecutter.project_slug}}/CODE_OF_CONDUCT.rst, {{cookiecutter.project_slug}}/CONTRIBUTING.rst
Might come in handy for (wannabe) ambitious / popular projects :)
=> Add a code of conduct

CONTRIBUTING.rst
_Small change just to test pushing PRs to upsream._
Add missing space after -r
=> Add missing space after -r

hooks/post_gen_project.py
there was a hook change necessary due to the '/src/' change, while being at it I followed alexanders lead moving from os.path to pathlib
=> - adapted to src structure... moved to pathlib

cookiecutter.json, docs/conf.py, hooks/pre_gen_project.py, requirements_dev.txt, ruff.toml, tests/test_bake_project.py, {{cookiecutter.project_slug}}/requirements_dev.txt
- Add Discord link to README
- Adding ruff support for the repo and in the generated python package
- fixes #709
=> ruff for linting and formatting

cookiecutter.json, {{cookiecutter.project_slug}}/pyproject.toml, {{cookiecutter.project_slug}}/src/{{cookiecutter.project_slug}}/cli.py, {{cookiecutter.project_slug}}/tests/test_{{cookiecutter.project_slug}}.py
Replaces Click and Argparse with Typer
=> Add typer for cli
