audreyfeldroy/cookiecutter-pypackage

{{cookiecutter.repo_name}}/Makefile

The current implementation does not remove any ``.egg`` files that ~~``tox``~~ ``python setup.py test`` adds to the root folder when it installs dependencies defined in ``setup.py``. I've amended the script to remove any and all ``.egg`` files when cleaning.
I also have a single-module Python project, which has a ``setup.py`` which looks like this:
setup(
[...]
py_modules=[
'package-name',
],
package_dir={'':
'src'},
[...]
)
Though perhaps a bug with ``setuptools``, this adds the ``egginfo`` folder to the ``src`` directory, rather than to the root directory. The script now also removes any and all ``egginfo`` folders.

Improved removal of egg-related files in Makefile

---

{{cookiecutter.repo_name}}/setup.py

Use double quote to avoid broken strings in the .py file if description or author name contains a single quote.

Use double quote to avoid broken strings

---

{{cookiecutter.repo_name}}/tests/test_{{cookiecutter.repo_name}}.py

with `python setup.py test` , `nosetests` or `py.test` this lines are unnecessary

remove unittest.main in test file

---

{{cookiecutter.repo_name}}/Makefile

Hello,
Here is a proposal for using `python -m webbrowser` to open user's browser for the commands in `Makefile`, which seems to be more portable than the Mac-only command.
Is this any good?
Thank you!
PS: btw, thanks for this awesome project, I've used to release a few packages already and it made everything so much easier. so, thank you! <3

Using webbrowser module instead of Mac-only open to open user's browser

---

.travis.yml

Hey @audreyr,
This fixes the build and cleans up `.travis.yml`: since boilerplate requirements file is only dev requirements, we can assume boilerplate has no runtime deps and so no need to install them anymore.
Looks good?

Fix build and simplify Travis config

---

{{cookiecutter.repo_name}}/Makefile
{{cookiecutter.repo_name}}/requirements_dev.txt

Hey @audreyr,
This adds a `make servedocs` target that does what `make docs` do and then watch for changes in the docs recompiling whenever you save.
It uses the `watchmedo` utility from the [watchdog](https://pypi.python.org/pypi/watchdog) package available in PyPI.
I've been using it in a few projects for a while, it has proved handy. :)
Does this look good?
Thanks,
Elias

Add make servedocs to watch for changes and recompile docs

---

{{cookiecutter.project_slug}}/CONTRIBUTING.rst

The tox environment specifies that we should test 3.5, so this guide should also say the same.

Add python 3.5 to contributing guide

---

{{cookiecutter.project_slug}}/setup.cfg

Otherwise you get a heap of noise:
```
./docs/conf.py:23:1: E265 block comment should start with '# '
./docs/conf.py:39:1: E265 block comment should start with '# '
./docs/conf.py:52:1: E265 block comment should start with '# '
./docs/conf.py:72:1: E265 block comment should start with '# '
./docs/conf.py:76:1: E265 block comment should start with '# '
./docs/conf.py:78:1: E265 block comment should start with '# '
./docs/conf.py:86:1: E265 block comment should start with '# '
./docs/conf.py:89:1: E265 block comment should start with '# '
./docs/conf.py:93:1: E265 block comment should start with '# '
./docs/conf.py:97:1: E265 block comment should start with '# '
./docs/conf.py:103:1: E265 block comment should start with '# '
./docs/conf.py:107:1: E265 block comment should start with '# ' …
```

Add Flake8 exclude for sphinx config

---

{{cookiecutter.project_slug}}/docs/installation.rst

Proposing more complete installation docs, suggesting pip install for
the stable releases and `python setup.py install` for installation from
sources.
For people that don't have pip, we point them to the Python installation in the hitchhiker's guide, that has nice instructions for having the basics (setuptools, pip and virtualenv): http://docs.python-guide.org/en/latest/starting/installation/

Add more complete installation instructions

---

.gitignore
.travis.yml
README.rst
cookiecutter.json
{{cookiecutter.project_slug}}/CONTRIBUTING.rst
{{cookiecutter.project_slug}}/Makefile
{{cookiecutter.project_slug}}/requirements_dev.txt
{{cookiecutter.project_slug}}/tests/test_{{cookiecutter.project_slug}}.py
{{cookiecutter.project_slug}}/tox.ini

I have added an option to the `cookiecutter.json` to switch between py.test and the regular test setup. I have been using this for my own projects and it seems to be a often heard feature request.

Switchable py.test support

---

{{cookiecutter.project_slug}}/tests/test_{{cookiecutter.project_slug}}.py

`repo_name` does not exist.
Don't know if changing from `capitalize` to `title` has a point, but it seems to work fine.

Do not use removed repo_name in PyTest template

---

{{cookiecutter.project_slug}}/setup.cfg

With current configuration, bumpversion will find&replace any occurrence of the version number in setup.py and my_project/init.py
This leads to trouble typically when setup.py mentions a dependency which has by hazard the same version number as our project (thus the dependency will get it version upped)
This fix precises to bumpversion a regex to match in the files in order to prevent such mistake.

Improve bumpversion regex matching

---

cookiecutter.json
tests/test_bake_project.py
{{cookiecutter.project_slug}}/LICENSE

This PR include support for choosing a license from a list of pre-defined ones. Currently, it only supports MIT and BSD, and MIT is the default one.
This PR solves https://github.com/audreyr/cookiecutter-pypackage/issues/62

include support for choosing between multiple licenses

---

README.rst
docs/tutorial.rst
{{cookiecutter.project_slug}}/README.rst

@willingc pointed out that the URL for Read The Docs has changed from readthedocs.org to readthedocs.io.
This closes https://github.com/audreyr/cookiecutter-pypackage/issues/150

Change readthedocs.org URLs to readthedocs.io.

---

requirements_dev.txt

I've added RequiresIO badges (https://github.com/audreyr/cookiecutter-pypackage/pull/161) but the badge on the README is red because these dependencies are out of date. This should get us to green.

Update tox and cryptography.

---

README.rst
{{cookiecutter.project_slug}}/README.rst

This adds the RequiresIO dependency badges to the README files and updates the documentation to include setup instructions. It also includes some links to sites that were mentioned already but didn't have associated URLs.
⚠️ Merge https://github.com/audreyr/cookiecutter-pypackage/pull/162 first so the new badge is green.
This closes https://github.com/audreyr/cookiecutter-pypackage/issues/147

RequiresIO badges and documentation links

---

{{cookiecutter.project_slug}}/Makefile

So, there are two main motivations for this PR:
1) remove Perl & Awk dependencies (side effect: clearer code) -- see #167 
2) avoid weird output when terminal doesn't support colors -- see #128 
Point 2 is "solved" by not using colors at all.
Is this okay or am I being overly conservative?

Replace perl & awk by python in make help (fixes #167 and closes #128)

---

.gitignore
Makefile
requirements_dev.txt

When we're doing changes in cookiecutter templates, we often have to generate an re-generate the project, to check if it's actually doing what we expect.
I wanted to try making this feedback loop a bit tigher, so I came up with this. The idea is, when you're editing the template, you'd do:
make watch
This will run `cookiecutter --no-input . --overwrite-if-exists` right away, and then every time you change something inside the template directory. I was using it while working on #169 and I quite liked it.
There is room for improvements, some things I thought:
1) it would be nice to re-run the command also when cookiecutter.json changes, or any of the hook scripts too (I couldn't figure out how to do this properly with `watchmedo`, it only watches directories)
2) it would be nice to support …

Add makefile with command to bake project watching for changes

---

.github/ISSUE_TEMPLATE.md

This adds a GitHub Issue template to the main root of cookiecutter pypackage.

Add GitHub issue template. Close #157

---

{{cookiecutter.project_slug}}/docs/index.rst

Correct indentation of the generated toc tree in index.rst so it displays authors properly.

Fix indentation of authors in docs

---

README.rst

As cookiecutter-pypackage do for every other package.

Add a link to the docs in README. Fix #192

---

{{cookiecutter.project_slug}}/README.rst

Read The Docs now uses .org for logins & badges. Also, they convert underscores in the repo name to dashes, sigh. They also changed the format for referencing the docs, to allow for different languages versions.

Fix generated read-the-docs badge

---

requirements_dev.txt

This will advise users with old cookiecutter versions to upgrade and prevent bug reports like https://github.com/audreyr/cookiecutter-pypackage/issues/99 and https://github.com/audreyr/cookiecutter-pypackage/issues/194

Specify minimal cookiecutter version (closes #194)

---

Makefile

This is a follow-up to https://github.com/audreyr/cookiecutter-pypackage/pull/170, mainly adding support for running replays.
Having this, if you want to keep baking a project using a specific set of arguments, you can:
* run it once with `cookiecutter .`, answer the prompt with the desired values
* then, run `make replay` to keep rebaking it.
You can also pass arbitrary options to cookiecutter through the `BAKE_OPTIONS` variable, e.g.: `make watch -e BAKE_OPTIONS=--replay -o other_output_dir`.
Does this look good?

Support replaying last run watching for changes

---

hooks/post_gen_project.py
tests/test_bake_project.py
{{cookiecutter.project_slug}}/README.rst

This removes the LICENSE file and omit badges and links for
ReadTheDocs, Travis and PyPI when project is not open source.
Looks good?

Add better handling for not open source (fixes #189)

---

appveyor.yml
{{cookiecutter.project_slug}}/Makefile

appveyor.yml
- include msys\bin to provide make
- no command for bdist_wheel when running python setup.py so replace with bdist
Makefile
- windows would not allow the complex python -c commands so replaced with a temp script.
Testing - Already had failed tests that are passing now. No new tests seemed to be required.

issue208-get-windows-builds-working

---

{{cookiecutter.project_slug}}/setup.cfg

`[wheel]` is legacy and doesn't support all the options. See the [bdist_wheel source](https://bitbucket.org/pypa/wheel/src/cf4e2d98ecb1f168c50a6de496959b4a10c6b122/wheel/bdist_wheel.py?at=default&fileviewer=file-view-default#bdist_wheel.py-119).

[wheel] -> [bdist_wheel]

---

{{cookiecutter.project_slug}}/LICENSE

Avoid parameterizing BSD license text by using revised version (text from: http://spdx.org/licenses/BSD-3-Clause.html).
This is better for users too, no need to update the license text in case they decide to change the project name.

Do not parameterize license text (fixes #227)

---

{{cookiecutter.project_slug}}/setup.py

According to https://pypi.python.org/pypi?%3Aaction=list_classifiers the name for GPL license classifier is incomplete and pypi will not accept the package.

Update GPL license classifier

---

tests/test_bake_project.py
{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/__init__.py

This fixes cases where the author name in `__init__.py` may cause a SyntaxError when the author name contains quotes.
e.g. for my name `Kevin Ndung'u` or other common names such as `O'Connor`

Account for author names with apostrophes

---

{{cookiecutter.project_slug}}/docs/index.rst

I guess the generated docs files are quite modified compared to what sphinx autogenerates, so we can remove this :)

Remove auto-generated comment :)

---

{{cookiecutter.project_slug}}/Makefile

If I run `make coverage` (Python 3.5), I get:
``` 
$> make coverage 
coverage run --source my_project py.test
No file to run: 'py.test'
Makefile:64: recipe for target 'coverage' failed
make: *** [coverage] Error 1
```
Correct invocation is to use the -m switch.
http://stackoverflow.com/a/16524426/405682

Invoke py.test correctly with coverage run

---

{{cookiecutter.project_slug}}/README.rst

With regards to the size of the `project_name` we should not add the same number of `=`

Use the correct number of `=` to make a title.

---

cookiecutter.json
tests/test_bake_project.py

Hyphens in project names were considered invalid as per the existing test.
It should be possible to support them by replacing hyphens by underscores when generating the default slug, as suggested in #250.

Support hyphens in project name. Fixes #250

---

{{cookiecutter.project_slug}}/MANIFEST.in

Use jinja's whitespace trimming to delete blank lines around `AUTHORS.rst` in `MANIFEST.in`.

Trim MANIFEST.in's blank lines

---

{{cookiecutter.project_slug}}/docs/index.rst

Hi,
Thanks for cookiecutter and this cool template!
I noticed a small bug: with `create_author_file=y`,`docs/index.rst` renders as
```
...
installation
usage
contributing
authorshistory
```
I had a quick look at `http://jinja.pocoo.org/docs/2.9/templates/#whitespace-control` but I couldn't figure out the 'right' way to fix it. So I did it the dumb way ;)
Edit: this was changed in the last commit https://github.com/audreyr/cookiecutter-pypackage/commit/af795bba4ae7fcabb4d117df01b07ba41b1d683d

Fix include of authors

---

.editorconfig

Without this, editorconfig-vim strips trailing whitespace in context and
old lines in unified diff (used frequently in the git add --patch
workflow), upon saving; the resulting diff fails to apply.

Keep trailing whitespace in diff files

---

{{cookiecutter.project_slug}}/setup.py

I recently created a project and using find_packages instead of manually defining where the packages are helped me get this working. With manually defining the packages it's easy to get in a situation where you get import errors (which I did). So it's really preferable to use `find_packages`

Use find_packages instead

---

{{cookiecutter.project_slug}}/.travis.yml
{{cookiecutter.project_slug}}/tox.ini

Tox-Travis supports mapping each Travis factor (a value of os, language,
python, environment variables, etc.) onto zero or more Tox environment
name factors, so as to fully take advantage of generative listing of
environments in Tox 1.8+.  It eases testing with a matrix of dependency
version combinations.
Examples are in https://tox-travis.readthedocs.io/en/stable/toxenv.html

Use Tox-Travis for environment selection

---

{{cookiecutter.project_slug}}/tox.ini

Without this, if we had <project_slug>/xyz.py, it would be importable
both as "<project_slug>.xyz" (correct) and as "xyz" (incorrect).

Remove package directory from PYTHONPATH

---

{{cookiecutter.project_slug}}/docs/.gitignore
{{cookiecutter.project_slug}}/docs/index.rst

Also .gitignore source ReST files generated by sphinx-apidoc.

Link auto-generated API into documentation index

---

.travis.yml
CONTRIBUTING.rst
README.rst
appveyor.yml
requirements_dev.txt
setup.py
tox.ini
{{cookiecutter.project_slug}}/.travis.yml
{{cookiecutter.project_slug}}/CONTRIBUTING.rst
{{cookiecutter.project_slug}}/requirements_dev.txt
{{cookiecutter.project_slug}}/setup.py
{{cookiecutter.project_slug}}/tox.ini

The Travis build of projects generated with this cookiecutter fail out of the box. The Travis build for the project itself is also failing. This pull request attempts to resolve this by:
- Updating the test setup of the project to match the setup of the generated project. The generated project seems to have a more modern approach, and keeping this uniform will improve maintainability.
- Update all dependencies to the most recent versions.
- Remove support for Python 2.6 (no longer supported by the Python core team) and Python 3.3 (not supported by Pytest)
Additionally, support for Python 3.6 was added, since this is the most recent version.

Fix failing Travis build

---

hooks/post_gen_project.py

[pytest recommends this:]( http://doc.pytest.org/en/latest/goodpractices.html)
> 
>  avoid “__init__.py” files in your test directories. This way your tests
>  can run easily against an installed version of mypkg, independently
>  from the installed package if it contains the tests or not.
> 
Let's make Python projects smarter

the tests directory should not contain __init__.py

---

{{cookiecutter.project_slug}}/tox.ini

Hi Audrey,
Literally doing what the comment says in tox.ini would break it:
py._iniconfig.ParseError: cookiecutter-pypackage/tox.ini:19: duplicate name 'deps'
Moving the comment would fix it.
Groet,
Maarten

More sane place for adding requirements.txt 2 tox.ini

---

{{cookiecutter.project_slug}}/CONTRIBUTING.rst

Would a reminder like this be acceptable? I found that I often forget how to use `bumpversion`, if I need to commit things myself or not etc., so having a cheat sheet somewhere would be useful.

reminder to maintainers on how to upgrade & deploy

---

{{cookiecutter.project_slug}}/Makefile

since the `clean` target removes the `dist` folder, it doesn't make sense to make it a dependency of `make release`. on the other hand, it would make a lot of sense to let it depend on `make dist`

fix release target in makefile

---

README.rst

English course link was pointing to the same place as the Spanish one.

:pencil: Fix English course link

---

README.rst
docs/pypi_release_checklist.rst
docs/travis_pypi_setup.rst
setup.cfg
{{cookiecutter.project_slug}}/CONTRIBUTING.rst
{{cookiecutter.project_slug}}/requirements_dev.txt

Fixes #424, fixes #437.
> I should probably add a sunsetting notice to the top of the README, saying this is not actively maintained and people should switch to one of the forked versions.
24 Oct 2017, https://github.com/peritus/bumpversion/issues/169#issuecomment-339023681

Use maintained bump2version instead of abandoned bumpversion

---

.travis.yml
CONTRIBUTING.rst
README.rst
appveyor.yml
setup.py
tox.ini
{{cookiecutter.project_slug}}/.travis.yml
{{cookiecutter.project_slug}}/CONTRIBUTING.rst
{{cookiecutter.project_slug}}/setup.py
{{cookiecutter.project_slug}}/tox.ini

Python 3.4 is EOL and no longer receiving security updates (or any updates) from the core Python team.
Version | Release date | Supported until
--- | ---------- | ----------
2.7 | 2010-07-03 | 2020-01-01
3.4 | 2014-03-16 | 2019-03-16
Source: https://en.wikipedia.org/wiki/CPython#Version_history
It's also little used. Here's the pip installs for `cookiecutter` from PyPI for June 2019:
| category | percent | downloads |
|----------|--------:|----------:|
| 3.7      |  49.40% |   152,691 |
| 2.7      |  24.74% |    76,463 |
| 3.6      |  20.75% |    64,135 |
| 3.5      |   4.54% |    14,030 |
| null     |   0.32% |       976 |
| 3.4      |   0.20% |       605 |
| 3.8      |   0.06% |       182 |
| 3.3      |   0.00% |         8 |
| 2.6      |   0.00% |         3 |
| 3.2      |   0.00% | …

Drop support for EOL Python 3.4

---

hooks/post_gen_project.py

Without this, you get 
```
py.test
================================ test session starts =================================
platform linux -- Python 3.7.1, pytest-3.8.2, py-1.7.0, pluggy-0.8.0
rootdir: /home/hayden/code/cache/old-cachepath, inifile: setup.cfg
collected 0 items / 1 errors                                                         
======================================= ERRORS =======================================
______________________ ERROR collecting tests/test_cachepath.py ______________________
ImportError while importing test module '/home/hayden/code/cache/old-cachepath/tests/test_cachepath.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../cachepath/tests/test_cachepath.py:9: in <module>
from cachepath import cachepath
E …
```

Fix py.test projects failing to import package

---

requirements_dev.txt

In the months to come, we need to guarantee python 2.7 support.

Update pytest 3.4.2 -> 4.6.5

---

README.rst

Hi.
Thanks for the great tool.
I've been dogfooding my own variant for a couple of projects, and I've now plucked up the courage to submit it!
You can have a look at the project at [github.com/briggySmalls/cookiecutter-pypackage](https://github.com/briggySmalls/cookiecutter-pypackage).
The differences are:
* Dependency tracking using pipenv
* Linting provided by both pylint and flake8 [executed by Tox]
* Formatting provided by yapf and isort [checked by Tox]
* Autodoc your code from Google docstring style (optional)
* All development tasks (lint, format, test, etc) wrapped up in a python CLI by invoke
Hopefully you agree to adding it to the repo.
Thanks again! ✌️

Add briggySmalls fork to list of alternatives

---

{{cookiecutter.project_slug}}/requirements_dev.txt

Hi, there's a tiny bug in the requirements_dev.txt Template which prevents correct representation of the selected command_line_interface option. If 'Click' is choosen it shows up in the Project's `setup.py` but not in its `requirements_dev.txt`. This patch fixes this tiny problem. Greetings & thanks for your awesome project, Sven

fixes: if Click is choosen it doesn't show up in the requirements_dev.txt

---

{{cookiecutter.project_slug}}/setup.py

Modify find_packages use in setup.py to find packages named `slug` or `slug.*`, where slug is the `project_slug`.
You can see that currently, only the root module is detected by find_packages. With the proposed fix, submodules are also detected.
Here is a MWE:
```
$ cookiecutter --no-input gh:audreyr/cookiecutter-pypackage
$ cd python_boilerplate
$ mkdir python_boilerplate/{foo, bar}
$ touch python_boilerplate/{foo, bar}/__init__.py
$ python -c 'import setuptools;print(setuptools.find_packages(include=["python_boilerplate"]))'
['python_boilerplate']
$ python -c 'import setuptools;print(setuptools.find_packages(include=["python_boilerplate", "python_boilerplate.*"]))'
['python_boilerplate', 'python_boilerplate.foo', 'python_boilerplate.bar']
```
Would close #423

Modify find_packages usage to find slug.* modules

---

{{cookiecutter.project_slug}}/setup.py

The "setup.py" says "Click>=6.0" while "requirements_dev.txt" says "Click==7.0"
So I wrote 7.0 in both places.

Bump click version to 7.0

---

cookiecutter.json
docs/console_script_setup.rst
tests/test_bake_project.py
{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/cli.py

This request creates an additional option to use argparse for console scripts. I realized rather late into the process that argparse was only added in Python 3.2, so this isn't likely to meet the criteria of Python 2.7 support. Figured I would submit it for conversation's sake and would very much appreciate any feedback.

Add Argparse CLI option, unit test and documentation

---

.gitignore
.travis.yml
CONTRIBUTING.rst
README.rst
appveyor.yml
setup.py
tests/test_bake_project.py
tox.ini
{{cookiecutter.project_slug}}/.gitignore
{{cookiecutter.project_slug}}/.travis.yml
{{cookiecutter.project_slug}}/CONTRIBUTING.rst
{{cookiecutter.project_slug}}/setup.py
{{cookiecutter.project_slug}}/tox.ini

Removes all instances of and references Python 2.7 from the codebase as well as cookiecutter.
Fixes #405 - Python 2.7 is end of life in less than 60 days.
Also adds `.vscode` to `.gitignore`, fixes broken test in win32, and resolves all flake8 linting errors

Remove python 2.7

---

{{cookiecutter.project_slug}}/.travis.yml
{{cookiecutter.project_slug}}/CONTRIBUTING.rst
{{cookiecutter.project_slug}}/README.rst

Any new project created would now land on the travis-ci.com domain.
https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps

Updates travis to the .com domain

---

README.rst
docs/tutorial.rst

Minor change to use the proper Read the Docs branding name.

Use "Read the Docs" instead of ReadTheDocs

---

docs/tutorial.rst

I have linked to the pypi page for publishing

The old link to help returns a 404 and was not to the pypi help.

---

docs/travis_pypi_setup.rst

Markdown headers were used instead of rst.

DOCS: Update travis_pypi_setup.rst

---

docs/prompts.rst

When I recently created a package, I was surprised to not be able to see my Travis builds using the README badge. And then I realized that the badge thinks that the repository is the project_slug which is formatted to have an \_ so that Python can properly import the package. I just wanted some clarification in the docs in case some other people are confused in the future.

Explain project_slug locations in docs

---

requirements_dev.txt
{{cookiecutter.project_slug}}/README.rst

Problem: Query parameter includes a typo.
Expected: `?version=latest`
Actual: `?badge=latest`
@audreyfeldroy @veit @pydanny

Fixed broken rtd docs link.

---

.travis.yml
CONTRIBUTING.rst
README.rst
docs/troubleshooting.rst
setup.py
tox.ini
{{cookiecutter.project_slug}}/.travis.yml
{{cookiecutter.project_slug}}/setup.py
{{cookiecutter.project_slug}}/tox.ini

Python 3.5 reached end of life according to https://www.python.org/dev/peps/pep-0478/ and should not be supported.
Therefore minimum Python version in setup.py is updated to 3.6, which is supported only till the end of 2021 according to https://devguide.python.org/#status-of-python-branches

Deprecate EOL Python 3.5 support

---

tests/test_bake_project.py
{{cookiecutter.project_slug}}/requirements_dev.txt
{{cookiecutter.project_slug}}/setup.cfg
{{cookiecutter.project_slug}}/setup.py

See: 
- https://github.com/pytest-dev/pytest-runner/issues/57
- https://github.com/pypa/setuptools/issues/1684
@audreyfeldroy

Remove deprecated setup_requires and pytest-runner

---

cookiecutter.json
tests/test_bake_project.py
{{cookiecutter.project_slug}}/Makefile
{{cookiecutter.project_slug}}/requirements_dev.txt

This is a first iteration with things kept simple. In the future I think we should do things like actually running both linters (flake and black) on the generated project via `tests/test_bake_project.py`.
Among other things I can also later provide a `make format` target that automatically fixes linter issues.
If things go as planned we can also add the `isort` linting option too

Introduces Black linter (disabled by default), closes #575

---

docs/tutorial.rst

Hi Folks
I have spotted and fixed a couple of broken links in the tutorial. One was related to travis-ci and the other a link to the PyPI checklist.
cheers

Fix broken links in the tutorial

---

README.rst

Adding waynerv/cookiecutter-pypackage to list of similar templates. Main differences:
- Using Poetry to manage packaging and dependencies.
- Run test, staging and release workflows with GitHub Actions.
- Added Pre-commit hooks to automatically run format, lint and static type check before every git commit.

Add new fork to Similar Cookiecutter Templates

---

{{cookiecutter.project_slug}}/requirements_dev.txt

The version of black used in this cookiecutter template [requires](https://github.com/psf/black/blob/21.7b0/setup.py#L75) `click>=7.1.2`. This conflict prevents tox from running tests.

Fix conflict between click and black

---

docs/tutorial.rst

Found some broken links while trying to figure out how to upload a package I made and last updated 7 years ago using cookiecutter-pypackage to PyPI.

Fix broken links in tutorial.rst

---

{{cookiecutter.project_slug}}/CONTRIBUTING.rst

The "getting started" instructions show the detailed bash commands to perform tests, linting etc.
Users should be taught there are handy/no-brainer make rules which take care of everything! 
Also those commands depend on the particular choices made at the generation of the package and may not be relevant.

Document the make rules instead of the plain commands

---

tests/test_bake_project.py

I've tested it locally on Fedora 39 machine, not sure if everything will work fine on other OSes

fix #715: Get tests running + remove obsolete Argparse tests

---

{{cookiecutter.project_slug}}/pyproject.toml

Not having this means namespaces aren't working because there are files not being added into the namespace. Which means tests inside the rendered package fails. We will address this in #735.
https://setuptools.pypa.io/en/latest/userguide/datafiles.html

Add missing package data

---

hooks/post_gen_project.py
{{cookiecutter.project_slug}}/pyproject.toml
{{cookiecutter.project_slug}}/src/{{cookiecutter.project_slug}}/__main__.py
{{cookiecutter.project_slug}}/src/{{cookiecutter.project_slug}}/cli.py

Hi,
on creating a python program I noticed I couldn't execute it since it didn't have a `__main__.py`.
Furthermore, I also couldn't start the debugger on that package for the very same reason.
This PR adds the missing `__main__.py` to the template to make it possible to both execute and debug the generated package.
I've seen [PR #481](https://github.com/audreyfeldroy/cookiecutter-pypackage/pull/481), where @znd4 already worked on a very similar PR which unfortunatelly was never merged.
Based on the coversation there, I've tried to pick up where he left.
Let me know if I'm missing anything here.
Sidenote: While adding this, I've noticed a couple things:
- The unit tests seem to be broken.
- When the user selects `"command_line_interface" = "Argparse`, the project still gets set up for …

Add __main__.py

---

{{cookiecutter.project_slug}}/pyproject.toml

This change allows versions to be set from the `__version__` attribute instead of manually defined in the pyproject config.

Set dynamic version

---

Makefile
cookiecutter.json
tests/test_bake_project.py
{{cookiecutter.project_slug}}/LICENSE

Hello,
Thank you very much for this excellent repo.
The PR adds the GNU Affero General Public License to the default options for licensing. The GNU AGPL is based on the GNU GPLv3, which you already support, but adds one requirement: if a developer modifies your project and runs it on a server, they must release their source code modifications. See [Why the Affero GPL](https://www.gnu.org/licenses/why-affero-gpl.html) for more information.
Thank you for your time and considering the PR.
Regards,
@dvklopfenstein

Add GNU Affero General Public License
